./latency_stxbtree_compress_random_int_a

./latency_stxbtree_compress_random_int_c

./latency_stxbtree_compress_random_int_e

./latency_stxbtree_compress_monoinc_int_a

./latency_stxbtree_compress_monoinc_int_c

./latency_stxbtree_compress_monoinc_int_e

./latency_stxbtree_compress_random_str_a

./latency_stxbtree_compress_random_str_c

./latency_stxbtree_compress_random_str_e

./latency_stxbtree_compress_email_a

./latency_stxbtree_compress_email_c

./latency_stxbtree_compress_email_e


