./latency_stxbtree_multi_compact_random_int_a

./latency_stxbtree_multi_compact_random_int_c

./latency_stxbtree_multi_compact_random_int_e

./latency_stxbtree_multi_compact_monoinc_int_a

./latency_stxbtree_multi_compact_monoinc_int_c

./latency_stxbtree_multi_compact_monoinc_int_e

./latency_stxbtree_multi_compact_random_str_a

./latency_stxbtree_multi_compact_random_str_c

./latency_stxbtree_multi_compact_random_str_e

./latency_stxbtree_multi_compact_email_a

./latency_stxbtree_multi_compact_email_c

./latency_stxbtree_multi_compact_email_e

